apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "5.46.7"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  values:
    global:
      image:
        repository: docker-upstream.apple.com/argoproj/argocd
        tag: v2.13.3
        imagePullPolicy: IfNotPresent
