apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "7.7.16" 
      sourceRef:
        kind: HelmRepository
        name: apple-remote-mirror
        namespace: flux-system
  timeout: 10m
  targetNamespace: argocd
  install:
    createNamespace: true
  values:
    global:
      image:
        repository: docker-upstream.apple.com/argoproj/argocd
        tag: v2.13.3
        imagePullPolicy: IfNotPresent
